[Rainmeter]
Update=200
AccurateText=1
DynamicWindowSize=1
OnRefreshAction=[!Move "0" "0"]

[Metadata]
Name=Clock
Author=Sayako
Information=A simple, minimalistic large clock skin.
Version=1.0
License=MIT

[Variables]
@include=#ROOTCONFIGPATH#\..\@Resources\Variables.inc

; --- Measures ---

[MeasureTime]
Measure=Time
Format=%H:%M:%S

[MeasureDate]
Measure=Time
Format=%m月%d日

[MeasureDay]
Measure=Time
Format=%A
Substitute="Monday":"月曜日","Tuesday":"火曜日","Wednesday":"水曜日","Thursday":"木曜日","Friday":"金曜日","Saturday":"土曜日","Sunday":"日曜日"

[MeasureBattery]
Measure=Plugin
Plugin=PowerPlugin
PowerState=Percent

; --- Meters ---

[MeterTime]
Meter=String
MeasureName=MeasureTime
FontFace=#FontFace#
FontSize=#FontSizeMain#
FontColor=#FontColor#
FontWeight=#FontWeight#
StringStyle=Normal
AntiAlias=1
Text=%1
StringAlign=CenterCenter
X=(#VSCREENAREAWIDTH# / 2)
Y=(#VSCREENAREAHEIGHT# / 4)
W=#VSCREENAREAWIDTH#
H=#VSCREENAREAHEIGHT#
DynamicVariables=1
SolidColor=0,0,0,1

[MeterSubInfo]
Meter=String
MeasureName=MeasureDate
MeasureName2=MeasureDay
MeasureName3=MeasureBattery
FontFace=#FontFace#
FontSize=#FontSizeSub#
FontColor=#FontColor#
StringStyle=Normal
AntiAlias=1
Text=%1 · %2 · %3% · #UserName#
StringAlign=CenterCenter
X=(#VSCREENAREAWIDTH# / 2)
Y=(#VSCREENAREAHEIGHT# / 4 + 100)
DynamicVariables=1
SolidColor=0,0,0,1
